
# Name of the project
name: 'my_new_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for 'my_new_project' project
profile: 'default'

# These configurations specify where dbt should look for different types of files
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# The configuration below will override models setting to be materialized as views or tables. 
models:
  +transient: false
  my_new_project:
    # Applies to all files under models/example/
    staging:
      +materialized: view
      +database: "{{ env_var('DBT_ENVIRONMENTS') }}_SILVER_DB"
      google_sheets:
        +schema: google_sheets
      sql_server_dbo:
        +schema: sql_server_dbo
      
    marts:
      +materialized: table
      +database: "{{ env_var('DBT_ENVIRONMENTS') }}_GOLD_DB"
      core:
        +schema: core
seeds:
  +schema: seed_data
  +database: "{{ env_var('DBT_ENVIRONMENTS') }}_BRONZE_DB"  
        
snapshots:
  +transient: false
  +target_database: "{{ env_var('DBT_ENVIRONMENTS') }}_SILVER_DB"
  +target_schema: snapshots
